Repository desenvolvendo-me/preco_certo, pull requests merged in 2021-06, with the labels that each got.

#58 Feature/new fields
  lib/preco_certo/employee.rb
  lib/preco_certo/storage/employees.csv
  spec/employee_spec.rb
Labels: feature

#59 Feature/new field in companies
  lib/preco_certo/company.rb
  lib/preco_certo/storage/companies.csv
  spec/company_spec.rb
Labels: feature

#60 Feat/equipment
  lib/preco_certo.rb
  lib/preco_certo/equipment.rb
  lib/preco_certo/storage/equipments.csv
  spec/equipment_spec.rb
Labels: feature

#62 Feat/calculate actual value of the equipment
  lib/preco_certo/equipment.rb
  spec/equipment_spec.rb
Labels: feature

#100 Migrate class company to rails
  .github/workflows/main.yml
  .gitignore
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/companies_controller.rb
  app/models/company.rb
  app/views/api/v1/companies/_company.json.jbuilder
  app/views/api/v1/companies/index.json.jbuilder
  app/views/api/v1/companies/show.json.jbuilder
  config/routes.rb
  db/migrate/20210616092826_create_companies.rb
  db/schema.rb
  db/seeds.rb
  lib/preco_certo.rb
  lib/preco_certo/company.rb
  lib/preco_certo/raw_material.rb
  lib/preco_certo/storage/companies.csv
  lib/preco_certo/storage/raw_materials.csv
  spec/company_spec.rb
  spec/employee_spec.rb
  spec/factories/companies.rb
  spec/markup_spec.rb
  spec/models/company_spec.rb
  spec/raw_material_spec.rb
  spec/requests/api/v1/companies_spec.rb
  spec/routing/api/v1/companies_routing_spec.rb
  spec/support/shoulda_matchers.rb
  yarn.lock
Labels: feature

#101 Updates rubocop and offenses
  .rubocop.yml
  app/controllers/api/v1/companies_controller.rb
  app/models/company.rb
  config/environments/test.rb
  db/migrate/20210616092826_create_companies.rb
  db/seeds.rb
  spec/factories/companies.rb
  spec/models/company_spec.rb
  spec/requests/api/v1/companies_spec.rb
  spec/routing/api/v1/companies_routing_spec.rb
  spec/support/shoulda_matchers.rb
  yarn.lock
Labels: improvement

#102 Migrate class product to rails
  .rubocop.yml
  app/controllers/api/v1/products_controller.rb
  app/models/product.rb
  app/views/api/v1/products/_product.json.jbuilder
  app/views/api/v1/products/index.json.jbuilder
  app/views/api/v1/products/show.json.jbuilder
  config/routes.rb
  db/migrate/20210617092806_create_products.rb
  db/schema.rb
  lib/preco_certo.rb
  lib/preco_certo/product.rb
  spec/factories/products.rb
  spec/models/product_spec.rb
  spec/product_spec.rb
  spec/requests/api/v1/products_spec.rb
  spec/routing/api/v1/products_routing_spec.rb
Labels: feature

#103 Feat/class manpower
  app/controllers/api/v1/manpowers_controller.rb
  app/models/manpower.rb
  app/views/api/v1/manpowers/_manpower.json.jbuilder
  app/views/api/v1/manpowers/index.json.jbuilder
  app/views/api/v1/manpowers/show.json.jbuilder
  config/routes.rb
  db/migrate/20210617091704_create_manpowers.rb
  db/schema.rb
  lib/preco_certo.rb
  spec/factories/manpowers.rb
  spec/manpower_spec.rb
  spec/models/manpower_spec.rb
  spec/requests/api/v1/manpowers_spec.rb
  spec/routing/api/v1/manpowers_routing_spec.rb
Labels: feature

#104 Feature/migrate class expense to rails
  .github/workflows/main.yml
  app/controllers/api/v1/expenses_controller.rb
  app/models/company.rb
  app/models/expense.rb
  app/views/api/v1/companies/_company.json.jbuilder
  app/views/api/v1/expenses/_expense.json.jbuilder
  app/views/api/v1/expenses/index.json.jbuilder
  app/views/api/v1/expenses/show.json.jbuilder
  config/routes.rb
  db/migrate/20210618082508_create_expenses.rb
  db/schema.rb
  db/seeds.rb
  lib/preco_certo.rb
  lib/preco_certo/expense.rb
  spec/expense_spec.rb
  spec/factories/expenses.rb
  spec/models/company_spec.rb
  spec/models/expense_spec.rb
  spec/requests/api/v1/expenses_spec.rb
  spec/routing/api/v1/expenses_routing_spec.rb
Labels: feature

#105 Feature/migrate class raw material to rails
  .idea/preco_certo.iml
  app/controllers/api/v1/raw_materials_controller.rb
  app/models/raw_material.rb
  app/views/api/v1/raw_materials/_raw_material.json.jbuilder
  app/views/api/v1/raw_materials/index.json.jbuilder
  app/views/api/v1/raw_materials/show.json.jbuilder
  config/routes.rb
  db/migrate/20210617092331_create_raw_materials.rb
  db/schema.rb
  lib/preco_certo.rb
  lib/preco_certo/raw_material.rb
  lib/preco_certo/storage/raw_materials.csv
  spec/factories/raw_materials.rb
  spec/models/raw_material_spec.rb
  spec/raw_material_spec.rb
  spec/requests/api/v1/raw_materials_spec.rb
  spec/routing/api/v1/raw_materials_routing_spec.rb
Labels: feature

#107 Feature/include docker compose in project
  .env.example
  .github/workflows/main.yml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/preco_certo.iml
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  bin/bundle
  config/database.yml
  db/schema.rb
  docker-compose.yml
Labels: feature, improvement

#116 Feature/migrate class job function
  app/models/job_function.rb
  db/migrate/20210623083640_create_job_functions.rb
  db/schema.rb
  db/seeds.rb
  lib/preco_certo.rb
  lib/preco_certo/job_function.rb
  spec/factories/job_functions.rb
  spec/factories_spec.rb
  spec/job_function_spec.rb
  spec/models/job_function_spec.rb
Labels: feature

#114 Feature/migrate class product raw material
  app/controllers/api/v1/product_raw_materials_controller.rb
  app/controllers/api/v1/raw_materials_controller.rb
  app/models/product.rb
  app/models/product_raw_material.rb
  app/models/raw_material.rb
  app/views/api/v1/product_raw_materials/_product_raw_material.json.jbuilder
  app/views/api/v1/product_raw_materials/index.json.jbuilder
  app/views/api/v1/product_raw_materials/show.json.jbuilder
  config/routes.rb
  db/migrate/20210622090432_create_product_raw_materials.rb
  db/migrate/20210622090810_add_net_price_to_raw_material.rb
  db/schema.rb
  lib/preco_certo.rb
  lib/preco_certo/product_raw_material.rb
  spec/factories/product_raw_materials.rb
  spec/factories/raw_materials.rb
  spec/models/product_raw_material_spec.rb
  spec/models/product_spec.rb
  spec/models/raw_material_spec.rb
  spec/product_raw_material_spec.rb
  spec/requests/api/v1/product_raw_materials_spec.rb
  spec/routing/api/v1/product_raw_materials_routing_spec.rb
Labels: feature

#117 Feature/productions goals
  .gitignore
  .idea/preco_certo.iml
  app/controllers/api/v1/production_goals_controller.rb
  app/models/production_goal.rb
  app/views/api/v1/production_goals/_production_goal.json.jbuilder
  app/views/api/v1/production_goals/index.json.jbuilder
  app/views/api/v1/production_goals/show.json.jbuilder
  config/routes.rb
  db/migrate/20210623234048_create_production_goals.rb
  db/schema.rb
  spec/factories/production_goals.rb
  spec/models/production_goal_spec.rb
  spec/requests/api/v1/production_goals_spec.rb
  spec/routing/api/v1/production_goals_routing_spec.rb
Labels: feature

#118 Hotfix/render json in browser
  app/controllers/api/v1/companies_controller.rb
  app/controllers/api/v1/expenses_controller.rb
  app/controllers/api/v1/manpowers_controller.rb
  app/controllers/api/v1/product_raw_materials_controller.rb
  app/controllers/api/v1/production_goals_controller.rb
  app/controllers/api/v1/products_controller.rb
  app/controllers/api/v1/raw_materials_controller.rb
  app/models/raw_material.rb
  config/routes.rb
  db/schema.rb
Labels: feature

#120 Doc/update readme
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  app/models/company.rb
  app/models/expense.rb
  app/models/job_function.rb
  app/models/manpower.rb
  app/models/product.rb
  app/models/product_raw_material.rb
  app/models/production_goal.rb
  app/models/raw_material.rb
  doc/preco_certo.postman_collection.json
  lib/tasks/auto_annotate_models.rake
Labels: Documentation
